In [17]:
#initializing code
import pandas as pd
schooldata=pd.read_csv("schools_complete.csv")
studentdata=pd.read_csv("students_complete.csv")

#district summary
totalschools=len(schooldata["School ID"])
totalstudents=len(studentdata["Student ID"])
totalbudget=schooldata["budget"].sum()/1000 #convert to thousands so that it doesn't display in log
averagemath=studentdata["math_score"].mean()
averagereading=studentdata["reading_score"].mean()

#initialize variables to be calculated
percentmath=0
percentreading=0
for item in studentdata["math_score"]:
    if item > 69:
        percentmath = percentmath+1
for item in studentdata["reading_score"]:
    if item > 69:
        percentreading = percentreading+1

percentmath=percentmath/totalstudents*100
percentreading=percentreading/totalstudents*100
percentoverall=(percentmath+percentreading)/2

districtsummary=pd.DataFrame({"Metric":['Total Schools','Total Students','Total Budget (thousands)','Average Math Score','Average Reading Score','% Passing Math','% Passing Reading','Overall Passing Rate'],
                              "Value":[totalschools,totalstudents,totalbudget,averagemath,averagereading,percentmath,percentreading,percentoverall]})

#school summary
schoolsummary=schooldata[['school_name','type','size','budget']]
perstudentbudget=[]
schoolmathavg=[]
schoolreadingavg=[]
schoolmathpass=[]
schoolreadingpass=[]
schooloverallpass=[]

#populate our blank lists by doing 1 loop for each school
for i in range(totalschools):
    studentbudget=int(schoolsummary.iloc[i,3])/int(schoolsummary.iloc[i,2])
    perstudentbudget.append(studentbudget)
    schoolmath=[]
    schoolreading=[]
    mathpass=[]
    readingpass=[]
    #within each school loop, run through a student loop
    for x in range(len(studentdata)):
        #within the student loop, find the student that matches the school and grab their scores
        if studentdata.iloc[x,4] == schoolsummary.iloc[i,0]:
            schoolmath.append(studentdata.iloc[x,6])
            if studentdata.iloc[x,6] > 69:
                mathpass.append(studentdata.iloc[x,6])
            schoolreading.append(studentdata.iloc[x,5])
            if studentdata.iloc[x,5] > 69:
                readingpass.append(studentdata.iloc[x,5])
    #process those matching scores into the metrics we want
    schoolmathavg.append(sum(schoolmath)/len(schoolmath))
    schoolreadingavg.append(sum(schoolreading)/len(schoolreading))
    schoolmathpass.append(len(mathpass)/len(schoolmath)*100)
    schoolreadingpass.append(len(readingpass)/len(schoolreading)*100)
    schooloverallpass.append((schoolmathpass[i]+schoolreadingpass[i])/2)
    
#append the finished lists back to the shool summary
schoolsummary['Per Student Budget']=perstudentbudget
schoolsummary['Average Math Score']=schoolmathavg
schoolsummary['Average Reading Score']=schoolreadingavg
schoolsummary['% Passing Math']=schoolmathpass
schoolsummary['% Passing Reading']=schoolreadingpass
schoolsummary['Overall Passing Rate']=schooloverallpass
schoolsummary

#top performing schools

,school_name,type,size,budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,Huang High School,District,2917,1910635,655.0,76.629414,81.182722,65.683922,81.316421,73.500171
1,Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.363852
2,Shelton High School,Charter,1761,1056600,600.0,83.359455,83.725724,93.867121,95.854628,94.860875
3,Hernandez High School,District,4635,3022020,652.0,77.289752,80.934412,66.752967,80.862999,73.807983
4,Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.265668
5,Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,93.867718,96.539641,95.203679
6,Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.586652
7,Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,66.680064,81.933280,74.306672
8,Holden High School,Charter,427,248087,581.0,83.803279,83.814988,92.505855,96.252927,94.379391
9,Pena High School,Charter,962,585858,609.0,83.839917,84.044699,94.594595,95.945946,95.270270
10,Wright High School,Charter,1800,1049400,583.0,83.682222,83.955000,93.333333,96.611111,94.972222
11,Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,66.366592,80.220055,73.293323
12,Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,66.057551,81.222432,73.639992
13,Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.804308
14,Thomas High School,Charter,1635,1043130,638.0,83.418349,83.848930,93.272171,97.308869,95.290520